EDR 5 - maintainers committee composition
pragma-org/amaru pull request #25
Opened 2024-10-11 14:55 UTC by Dam-CZ

2024-11-07 16:37 UTC, AndrewWestberg approved these changes

2024-11-12 09:13 UTC, KtorZ commented on engineering-decision-records/005-amaru-maintainers-committee.md
> +[@sebastienGllmt]: https://github.com/sebastienGllmt
Would it make sense to have the general bounded-contexts be reflected here, with their responsible maintainers?

2025-01-09 13:19 UTC, wolf31o2 requested changes

2025-01-09 13:19 UTC, wolf31o2 commented on engineering-decision-records/005-amaru-maintainers-committee.md
> +- GO Node owner: [Chris Gianelloni](https://github.com/wolf31o2)
```suggestion
- Dingo owner: [Chris Gianelloni](https://github.com/wolf31o2)
```

2025-01-16 11:10 UTC, merged